### ISSUE TITLE
Extra Space and overlapping text

### ISSUE THREAD

**Issue by ImanGhader** [ImanGhader/temp#6]
I don't know what is causing this small white gap at the right of the grid. It's very small but it's there.
I also don't know why the caption of the images are extended outside of their own images. They are set in a ul and each piece is inside an li with an <img> and <p>.

![screen shot 2014-11-18 at 6 02 33 pm](https://cloud.githubusercontent.com/assets/6371797/5097845/369e0fa6-6f4d-11e4-822e-f6258e054a39.png)

**Comment by thomasjbradley** [comment]
The space below the images is mentioned in #3.

Get rid of the `white-space: nowrap` on the `.pieces p` tags.
